# Change these first
owner: riccardocalligaro # Your GitHub organization or username, where this repository lives
repo: polydesk-upptime # The name of this repository

sites:
  - name: Demo
    url: https://demo.polydesk.app/
    headers:
      - "User-Agent: Polydesk uptime"
  - name: Demo API
    url: https://demo.polydesk.app/api/v1/
    headers:
      - "User-Agent: Polydesk uptime"
    expectedStatusCodes:
      - 404
  # san gaetano
  - name: San Gaetano
    icon: https://sangaetano.polydesk.app/favicon.ico
    url: https://sangaetano.polydesk.app/
    headers:
      - "User-Agent: Polydesk uptime"
  - name: San Gaetano API
    icon: https://sangaetano.polydesk.app/favicon.ico
    url: https://sangaetano.polydesk.app/api/v1/
    headers:
      - "User-Agent: Polydesk uptime"
    expectedStatusCodes:
      - 404
  - name: BieloHUB
    icon: https://bielohub.polydesk.app/favicon.ico
    url: https://bielohub.polydesk.app/
    headers:
      - "User-Agent: Polydesk uptime"
  - name: BieloHUB API
    icon: https://bielohub.polydesk.app/favicon.ico
    url: https://bielohub.polydesk.app/api/v1/
    headers:
      - "User-Agent: Polydesk uptime"
    expectedStatusCodes:
      - 404
  # butterfly
  - name: Butterfly
    icon: https://butterfly.polydesk.app/favicon.ico
    url: https://butterfly.polydesk.app/
    headers:
      - "User-Agent: Polydesk uptime"

  - name: Butterfly API
    icon: https://butterfly.polydesk.app/favicon.ico
    url: https://butterfly.polydesk.app/api/v1/
    headers:
      - "User-Agent: Polydesk uptime"
    expectedStatusCodes:
      - 404
  # gruppo paim
  - name: Gruppo Paim
    icon: https://www.gruppopaim.it/img/favicon.png
    url: https://gruppopaim.polydesk.app/
    headers:
      - "User-Agent: Polydesk uptime"
  - name: Gruppo Paim API
    icon: https://www.gruppopaim.it/img/favicon.png
    url: https://gruppopaim.polydesk.app/api/v1/
    headers:
      - "User-Agent: Polydesk uptime"
    expectedStatusCodes:
      - 404
  # radius lab
  - name: Euromedica
    icon: https://status.polydesk.app/radiuslab.ico
    url: https://euromedica.polydesk.app/
    headers:
      - "User-Agent: Polydesk uptime"
  - name: Euromedica API
    icon: https://status.polydesk.app/radiuslab.ico
    url: https://euromedica.polydesk.app/api/v1/
    headers:
      - "User-Agent: Polydesk uptime"
    expectedStatusCodes:
      - 404
  - name: Sito dimostrativo
    url: https://polydesk.app/
    headers:
      - "User-Agent: Polydesk uptime"

status-website:
  themeUrl: https://status.polydesk.app/custom-status.css
  favicon: https://polydesk.app/favicon.ico
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.polydesk.app
  # baseUrl: /your-repo-name
  logoUrl: https://polydesk.app/polydesk_cirlce.svg
  name: Polydesk
